//
//  ManifoldRayCounterTests.swift
//  CodeAdvent
//
//  Created by Eugene Mokeiev on 09.12.2025.
//

import Testing
@testable import CodeAdvent
import Foundation

struct ManifoldRayCounterTests {
    
    @Test func testExampleManifold() {
        let sut = ManifoldRayCounter(
            rawString:
                """
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............
                """
        )
        #expect(sut.numberOfBeamSplits == 21)
    }
}
